### ISSUE TITLE
Please add a version number

### ISSUE THREAD

**Issue by jtbx** [jobcmax/maxfetch#5]
I'm packaging this for Arch Linux and the AUR, and it requires a version number. For now I'm going to have to mark it as 0.1.0, but it would be nice if you could invoke maxfetch with a `-V` or a `--version` argument and it would show `maxfetch version $VERSION` or something similar.

**Comment by natewhar** [comment]
fixed, you can now check maxfetch version using the --version argument.

**Comment by jtbx** [comment]
Thank you
